name: Build and Release MenuSite

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Create ExportOptions.plist
      run: |
        cat > ExportOptions.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>mac-application</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>stripSwiftSymbols</key>
            <true/>
        </dict>
        </plist>
        EOF
        
    - name: Build and export app
      run: |
        # Build the app
        xcodebuild -project menusite.xcodeproj \
          -scheme menusite \
          -configuration Release \
          -derivedDataPath build \
          -archivePath build/menusite.xcarchive \
          archive
          
        # Export the app
        xcodebuild -exportArchive \
          -archivePath build/menusite.xcarchive \
          -exportPath build/export \
          -exportOptionsPlist ExportOptions.plist
        
    - name: Create app bundle
      run: |
        # Find the exported app
        APP_PATH=$(find build/export -name "*.app" -type d | head -1)
        echo "Found app at: $APP_PATH"
        
        # Create zip file
        cd build/export
        zip -r ../../menusite-macos.zip *.app
        cd ../..
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: menusite-macos
        path: menusite-macos.zip
        
    - name: Get version from tag
      if: startsWith(github.ref, 'refs/tags/v')
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: menusite-macos.zip
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: MenuSite ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## MenuSite ${{ steps.get_version.outputs.VERSION }}
          
          ### Installation Instructions
          1. Download `menusite-macos.zip`
          2. Unzip the file
          3. Drag `menusite.app` to your Applications folder
          4. Right-click and select "Open" on first launch (security requirement for unsigned apps)
          
          ### Features
          - Website viewer in your menu bar
          - Favicon auto-detection and custom icons
          - Multiple website instances
          - Mobile website rendering
          - Configurable window sizes
          
          ### Requirements
          - macOS 11.0 or later
          
          **Note**: This app is not code-signed, so you may see a security warning on first launch.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}